import crypto from "node:crypto";
import express from "express";
import { fileURLToPath } from "node:url";
import path from "node:path";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PORT = Number(process.env.PORT ?? "8080");
const SPRITES_API = process.env.SPRITES_API_URL ?? "https://api.sprites.dev";

const app = express();
app.use(express.json());
app.use(express.static(path.join(__dirname, "public")));

// ---------------------------------------------------------------------------
// Generate the setup.sh script for a given config
// ---------------------------------------------------------------------------
function generateSetupScript(config) {
  const envExports = [];
  if (config.anthropicKey) envExports.push(`export ANTHROPIC_API_KEY='${config.anthropicKey}'`);
  if (config.openaiKey) envExports.push(`export OPENAI_API_KEY='${config.openaiKey}'`);
  if (config.googleKey) envExports.push(`export GOOGLE_API_KEY='${config.googleKey}'`);
  if (config.gatewayToken) envExports.push(`export OPENCLAW_GATEWAY_TOKEN='${config.gatewayToken}'`);

  const gatewayArgs = ["npx", "openclaw", "gateway"];
  if (config.gatewayAuth === "open") {
    gatewayArgs.push("--allow-unconfigured");
  }

  return `#!/usr/bin/env bash
set -euo pipefail

# OpenClaw on Sprites — idempotent setup
# Generated by openclaw-builder

DIR=/home/sprite/claw
KEEP_RUNNING="$DIR/sprite-keep-running.sh"
START_SH="$DIR/start.sh"
CONFIG="$DIR/openclaw.json"
SERVICE_NAME="openclaw"
GATEWAY_PORT=18789

log() { echo "[setup] $*"; }

mkdir -p "$DIR"

# --- sprite-keep-running.sh (always overwrite — it's ours) ---

log "Installing sprite-keep-running.sh"
cat > "$KEEP_RUNNING" << 'KEEPEOF'
#!/usr/bin/env bash
set -euo pipefail

TASK_NAME="keep-running-$$"
EXPIRE="1h"
REFRESH_INTERVAL=300

task_post() {
  sprite-env curl -s -X POST /v1/tasks \\
    -d "{\\"name\\": \\"$TASK_NAME\\", \\"expire\\": \\"$EXPIRE\\"}" \\
    >/dev/null 2>&1 || true
}

task_delete() {
  sprite-env curl -s -X DELETE "/v1/tasks/$TASK_NAME" \\
    >/dev/null 2>&1 || true
}

cleanup() {
  task_delete
  if [ -n "\${REFRESH_PID:-}" ] && kill -0 "$REFRESH_PID" 2>/dev/null; then
    kill "$REFRESH_PID" 2>/dev/null || true
    wait "$REFRESH_PID" 2>/dev/null || true
  fi
}
trap cleanup EXIT

task_post
echo "[sprite-keep-running] Registered activity task: $TASK_NAME"

(
  while true; do
    sleep "$REFRESH_INTERVAL"
    task_post
  done
) &
REFRESH_PID=$!

if [ $# -gt 0 ]; then
  echo "[sprite-keep-running] Running: $*"
  set +e
  "$@"
  EXIT_CODE=$?
  set -e
  echo "[sprite-keep-running] Command exited with status $EXIT_CODE"
  exit "$EXIT_CODE"
else
  echo "[sprite-keep-running] No command given, running keep-alive loop"
  wait "$REFRESH_PID"
fi
KEEPEOF
chmod +x "$KEEP_RUNNING"

# --- environment variables in .profile ---

log "Setting environment variables in .profile"
${envExports.map((e) => `grep -qxF '${e}' /home/sprite/.profile 2>/dev/null || echo '${e}' >> /home/sprite/.profile`).join("\n")}

# Source them for this session
${envExports.join("\n")}

# --- start.sh (create if missing) ---

if [ -f "$START_SH" ]; then
  log "start.sh already exists, skipping"
else
  log "Creating start.sh"
  cat > "$START_SH" << 'EOF'
#!/usr/bin/env bash
cd /home/sprite/claw
source /home/sprite/.profile 2>/dev/null || true
export OPENCLAW_CONFIG_PATH=/home/sprite/claw/openclaw.json
export OPENCLAW_STATE_DIR=/home/sprite/claw
exec /home/sprite/claw/sprite-keep-running.sh ${gatewayArgs.join(" ")}
EOF
  chmod +x "$START_SH"
fi

# --- openclaw.json (merge defaults, don't overwrite) ---

DEFAULTS=$(cat << JSON
{
  "agents": {
    "defaults": {
      "workspace": "/home/sprite/claw/workspace"
    }
  },
  "gateway": {
    "mode": "local",
    "controlUi": {
      "allowedOrigins": ["${config.spriteUrl}"]
    }
  }
}
JSON
)

if [ -f "$CONFIG" ]; then
  log "Merging defaults into existing openclaw.json"
  EXISTING=$(cat "$CONFIG")
  echo "$DEFAULTS" | jq -s '.[0] * .[1]' - <(echo "$EXISTING") > "$CONFIG.tmp"
  mv "$CONFIG.tmp" "$CONFIG"
else
  log "Creating openclaw.json"
  echo "$DEFAULTS" | jq . > "$CONFIG"
fi

# --- workspace dir ---

mkdir -p "$DIR/workspace"

# --- sprite service (create or update) ---

EXISTING_SERVICE=$(sprite-env curl -s "/v1/services/$SERVICE_NAME" 2>/dev/null || echo "")

if echo "$EXISTING_SERVICE" | jq -e '.name' >/dev/null 2>&1; then
  log "Updating existing openclaw service"
  sprite-env curl -s -X POST "/v1/services/$SERVICE_NAME/stop" >/dev/null 2>&1 || true
  sleep 1
fi

log "Creating openclaw service"
sprite-env curl -s -X PUT "/v1/services/$SERVICE_NAME" \\
  -d "{\\"cmd\\": \\"$START_SH\\", \\"args\\": [], \\"needs\\": [], \\"http_port\\": $GATEWAY_PORT}" \\
  >/dev/null

# --- start it ---

log "Starting openclaw service"
sprite-env services start "$SERVICE_NAME" 2>/dev/null || true

log "Done. OpenClaw is available at your Sprite URL."
`;
}

// ---------------------------------------------------------------------------
// Deploy endpoint — streams progress via SSE
// ---------------------------------------------------------------------------
app.post("/api/deploy", async (req, res) => {
  const {
    apiToken,
    spriteName,
    anthropicKey,
    openaiKey,
    googleKey,
    gatewayAuth,
    gatewayCredential,
  } = req.body;

  if (!apiToken) return res.status(400).json({ error: "API token is required" });
  if (!anthropicKey && !openaiKey && !googleKey) {
    return res.status(400).json({ error: "At least one API key is required" });
  }

  // Generate claw-* name if not provided
  const adjectives = ["swift","deep","wild","cold","dark","keen","bold","calm","fast","warm"];
  const animals = ["hawk","wolf","bear","fox","lynx","crow","owl","elk","ram","jay"];
  const randomName = `claw-${adjectives[Math.floor(Math.random() * adjectives.length)]}-${animals[Math.floor(Math.random() * animals.length)]}`;
  const name = spriteName?.trim() || randomName;

  // Gateway token — use provided credential or generate one
  const gatewayToken = gatewayCredential?.trim() || crypto.randomBytes(32).toString("hex");

  // SSE
  res.writeHead(200, {
    "Content-Type": "text/event-stream",
    "Cache-Control": "no-cache",
    Connection: "keep-alive",
  });

  const send = (type, data) => res.write(`data: ${JSON.stringify({ type, ...data })}\n\n`);
  const step = (msg) => send("step", { message: msg });
  const ok = (msg) => send("ok", { message: msg });
  const fail = (msg) => { send("error", { message: msg }); res.end(); };

  // Sprites API helpers
  async function api(method, urlPath, body) {
    const resp = await fetch(`${SPRITES_API}${urlPath}`, {
      method,
      headers: {
        Authorization: `Bearer ${apiToken}`,
        "Content-Type": "application/json",
      },
      body: body ? JSON.stringify(body) : undefined,
    });
    const text = await resp.text();
    let json; try { json = JSON.parse(text); } catch { json = null; }
    if (!resp.ok) throw new Error(json?.error || json?.errors?.join(", ") || text || `HTTP ${resp.status}`);
    return json;
  }

  async function exec(spriteName, cmd) {
    const params = new URLSearchParams();
    params.append("cmd", "bash");
    params.append("cmd", "-c");
    params.append("cmd", cmd);

    const resp = await fetch(
      `${SPRITES_API}/v1/sprites/${encodeURIComponent(spriteName)}/exec?${params}`,
      { method: "POST", headers: { Authorization: `Bearer ${apiToken}` } },
    );
    const text = await resp.text();
    if (!resp.ok) throw new Error(`exec ${resp.status}: ${text.slice(0, 500)}`);
    return text;
  }

  try {
    // Step 1: Create the sprite
    step(`Creating sprite "${name}"...`);
    let sprite;
    try {
      sprite = await api("POST", "/v1/sprites", { name });
    } catch (e) {
      return fail(`Failed to create sprite: ${e.message}`);
    }
    ok(`Sprite created: ${sprite.url}`);

    // Step 2: Wait for sprite to be ready
    step("Starting sprite...");
    let ready = false;
    for (let i = 0; i < 40; i++) {
      try {
        const info = await api("GET", `/v1/sprites/${encodeURIComponent(name)}`);
        if (info.status === "running" || info.status === "warm") {
          ready = true;
          break;
        }
      } catch { /* keep trying */ }
      // Poke the sprite URL to trigger startup
      fetch(sprite.url).catch(() => {});
      await new Promise((r) => setTimeout(r, 3000));
    }
    if (!ready) return fail("Sprite failed to start within 2 minutes");
    ok("Sprite is running");

    // Step 3: Run the setup script
    step("Running setup (installing OpenClaw, configuring service)...");
    try {
      const setupScript = generateSetupScript({
        anthropicKey,
        openaiKey,
        googleKey,
        gatewayToken,
        gatewayAuth: gatewayAuth || "password",
        spriteUrl: sprite.url,
      });
      const output = await exec(name, setupScript);
      // Stream the setup log lines as info
      for (const line of output.split("\n").filter((l) => l.startsWith("[setup]"))) {
        send("info", { message: line });
      }
    } catch (e) {
      return fail(`Setup failed: ${e.message}`);
    }
    ok("OpenClaw installed and service started");

    // Step 4: Wait for gateway to be reachable
    step("Waiting for gateway to come online...");
    let gwReady = false;
    for (let i = 0; i < 20; i++) {
      try {
        const resp = await fetch(sprite.url, { redirect: "follow" });
        if (resp.ok || resp.status === 401 || resp.status === 403) {
          gwReady = true;
          break;
        }
      } catch { /* retry */ }
      await new Promise((r) => setTimeout(r, 3000));
    }
    if (gwReady) {
      ok("Gateway is online");
    } else {
      ok("Service started (gateway may still be booting)");
    }

    // Done
    send("done", {
      message: "OpenClaw is deployed!",
      spriteUrl: sprite.url,
      gatewayUrl: `wss://${sprite.url.replace("https://", "")}`,
      gatewayToken,
      spriteName: name,
      curlSetup: `curl -fsSL ${sprite.url}/setup.sh | bash`,
    });
    res.end();
  } catch (e) {
    fail(`Unexpected error: ${e.message}`);
  }
});

app.listen(PORT, "0.0.0.0", () => {
  console.log(`OpenClaw Builder listening on http://0.0.0.0:${PORT}`);
});
